### ISSUE TITLE
Implementation of objective (2.12)

### ISSUE THREAD

**Issue by h2o64** [malbergo/stochastic-interpolants#1]
Hello,

I was reading through the `loss_per_sample_sv` function in `interflow/stochastic_interpolant.py` and I found an irregularity between the theoretical loss (2.12) [1] as I would expect to see `dtIt + dt_gam * z` in the right member here https://github.com/malbergo/stochastic-interpolants/blob/938bd9db80d9d8a85e187699877ac0de17ffb040/interflow/stochastic_interpolant.py#L326. Instead the variable `dt_gam` is unused. Maybe it's a legacy part from [2].

[1] Albergo, M. S., Boffi, N. M., & Vanden-Eijnden, E. (2023). Stochastic Interpolants: A Unifying Framework for Flows and Diffusions. arXiv preprint arXiv:2303.08797.
[2] Albergo, M. S., & Vanden-Eijnden, E. (2022). Building normalizing flows with stochastic interpolants. arXiv preprint arXiv:2209.15571.

**Comment by h2o64** [comment]
I figured that the loss minimized was (2.25) and not (2.12)

**Comment by malbergo** [comment]
Hi @h2o64. Yes, sorry for the confusion. One has the choice to minimize b_t(x) and s_t(x), or they can minimize v_t(x) and s_t(x). We chose the latter for this implementation. Thanks for your question.
