### ISSUE TITLE
question on the flower dataset

### ISSUE THREAD

**Issue by hamrel-cxu** [malbergo/stochastic-interpolants#5]
First of all, thank you for the great works!

I am trying to run on the flower dataset, which comes from "Maria-Elena Nilsback and Andrew Zisserman. A visual vocabulary for flower classification. In IEEE Conference on Computer Vision and Pattern Recognition, volume 2, pp. 1447–1454, 2006"

However, upon visiting the official website (https://www.robots.ox.ac.uk/~vgg/data/flowers/) maintained by these authors, I noticed that both flower datasets contain far fewer images compared to those referenced in your research. Specifically, in Table 4 of your paper (https://arxiv.org/pdf/2209.15571.pdf), it states that the flower dataset comprises 315,123 images, each sized 128x128 pixels, whereas the official dataset seems to have less than 9000 images. Hence, I'm inquiring whether you could provide a link to the dataset utilized in your experiments.

Thank you very much!

**Comment by malbergo** [comment]
Hi @hamrel-cxu, that seems like the wrong info I provided. Indeed it is a small dataset. There is only the one from the Oxford page.

**Comment by malbergo** [comment]
https://scalable-interpolant.github.io/ There is a full set of functional code for images available here.

**Comment by hamrel-cxu** [comment]
@malbergo Thank you for your prompt response and for sharing the code! Just to be clear, is this 17-category dataset (https://www.robots.ox.ac.uk/~vgg/data/flowers/17/index.html) the one you actually used? There is another 102-category one (https://www.robots.ox.ac.uk/~vgg/data/flowers/102/index.html) provided by the same authors but it seems to come from a later paper (not the one you cited).

**Comment by malbergo** [comment]
I used the large one.
